backend:
  name: git-gateway
  branch: main

media_folder: "gallery"
public_folder: "/gallery"

collections:
  - name: "anilar"
    label: "Anılar"
    folder: "_anilar"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime"}
      - {label: "Açıklama", name: "description", widget: "text"}
      - {label: "Resim", name: "image", widget: "image"}
      - {label: "Tarih", name: "tarih", widget: "string"}